bash /home/osdi/ae/scripts/fig4/mcd-cl.sh
sleep 3
bash /home/osdi/ae/scripts/fig4/mcd-u.sh
sleep 3
bash /home/osdi/ae/scripts/fig4/gpr.sh
sleep 3
bash /home/osdi/ae/scripts/fig4/atc.sh
sleep 3
bash /home/osdi/ae/scripts/fig4/df.sh
sleep 3
bash /home/osdi/ae/scripts/fig4/ws.sh
sleep 3
bash /home/osdi/ae/scripts/fig4/mwc.sh
sleep 3
bash /home/osdi/ae/scripts/fig4/mpvc.sh
sleep 3
